### ISSUE TITLE
Fatal error on reference parsing

### ISSUE THREAD

**Issue by Vitaliy-1** [Vitaliy-1/docxToJats#12]
Explore circumstances where citation can be recognized as a JSON but not in CSL format. Correspondent error:
```
PHP Notice:  Undefined property: stdClass::$plainCitation in /home/doc/OJS/development/e-med/ojs/plugins/generic/docxConverter/docxToJats/src/docx2jats/objectModel/body/Reference.php on line 57
PHP Notice:  Undefined property: stdClass::$formattedCitation in /home/doc/OJS/development/e-med/ojs/plugins/generic/docxConverter/docxToJats/src/docx2jats/objectModel/body/Reference.php on line 61
PHP Fatal error:  Uncaught TypeError: Return value of docx2jats\objectModel\body\Reference::getCslId() must be of the type int, string returned in /home/doc/OJS/development/e-med/ojs/plugins/generic/docxConverter/docxToJats/src/docx2jats/objectModel/body/Reference.php:32
Stack trace:
#0 /home/doc/OJS/development/e-med/ojs/plugins/generic/docxConverter/docxToJats/src/docx2jats/objectModel/body/Field.php(85): docx2jats\objectModel\body\Reference->getCslId()
#1 /home/doc/OJS/development/e-med/ojs/plugins/generic/docxConverter/docxToJats/src/docx2jats/objectModel/body/Field.php(59): docx2jats\objectModel\body\Field->processRuns()
#2 /home/doc/OJS/development/e-med/ojs/plugins/generic/docxConverter/docxToJats/src/docx2jats/objectModel/body/Par.php(108): docx2jats\objectModel\body\Field->addContent()
#3 /home/doc/OJS/development/e-med/ojs/plugins/generic/docxConverter/docxToJats/src/docx2jats/objectModel/body/Par.php(59): docx2jats\objectModel\body\Par->setContent()
#4 /home/doc/OJS/development/e-med/ojs/plugins/generic/docxConverte in /home/doc/OJS/development/e-med/ojs/plugins/generic/docxConverter/docxToJats/src/docx2jats/objectModel/body/Reference.php on line 32
```

**Comment by Vitaliy-1** [comment]
The error comes from Mendeley MS Word plugin which also injects references in CSL format into DOCX; in this case `csl_id` can have string data type.
